backend:
  name: github
  repo: matthewkeil/CODEified
  branch: master
  site_domain: codeified.org
  base_url: http://localhost:3001/netlify
local_backend: true
media_folder: 'static/media'
public_folder: 'static/media'
site_url: https://localhost:3000
collections:
  - name: categories
    label: Categories
    folder: content/categories
    create: true
    slug: '{{slug}}'
    identified_field: name
    fields:
      - { label: Name, name: name, widget: string }
      - {
          label: Description,
          name: description,
          widget: markdown,
          required: false,
        }
  - name: posts
    label: Posts
    folder: content/posts
    preview_path: '{{slug}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string, required: false }
      - { name: author, label: Author, widget: string }
      - { name: hero, lable: Hero Image, widget: image }
      - {
          name: prominent,
          lable: Prominent,
          widget: boolean,
          default: false,
          required: false,
        }
      - {
          name: published,
          label: Publish Date,
          widget: datetime,
          default: true,
          required: true,
        }
      - {
          name: updated,
          label: Updated Date,
          widget: datetime,
          default: true,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
      - {
          label: Category,
          name: category,
          widget: relation,
          collection: categories,
          searchFields: name,
          valueField: name,
          multiple: true,
        }
